### ISSUE TITLE
Add review-pr command

### ISSUE THREAD

**Issue by gotcha** [devpi/devpi-pr#2]
It will store the current serial locally.
And use it when approving or rejecting.

It does display the serial being stored for future use.

It can be called multiple times.

If the serial is stored and has not changed, just display and do not complain.
If it has changed, mention that you need to override and ask acknowledgement (to avoid it goes unseen)

There could be a --override-serial flag that can be used to state that the user already knows he needs to override serial.

**Comment by fschulze** [comment]
Done
